image: node # 使用node 镜像

build:
  only:
    - master # 只有master更新的时候才执行命令
  script: # 执行的命令
    - npm install --registry https://registry.npm.taobao.org
    - hexo cl && hexo g
    - rm -rf /usr/local/nginx/html/*
    - cp -r public/* /usr/local/nginx/html/
  tags:
    - zfwfyblog