language: node_js  #设置语言

node_js: "lts/*"  #设置相应的版本

cache:
  directories:
    - node_modules

install:
  - npm install  #安装hexo及插件

before_script:
  - cd themes/sagiri
  - npm install
  - cd ../..

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "Layne666"  #修改name
  - git config user.email "791270330@qq.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" hexo-public:hexo-public  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - master  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/Layne666/layne666.site.git  #设置GH_REF，注意更改yourname
